### ISSUE TITLE
Question about migration

### ISSUE THREAD

**Issue by wojnas** [RocketChat/filestore-migrator#11]
Hello,
I have question about migration from mongodb gridfs to filesystem scenario.
I used command:
`filestore-migrator -action=migrate  -databaseUrl=mongodb://mongo:27017/rocketchat -sourceType=girdfs -destinationType=fs   -destinationUrl=/app/uploads.`
It works fine, i have attachements in file system, and I can open it in application. 
What about co mongdb database size - collection rocketchat_uploads.chunks still have migrated objects.

How to safty shrik database size and delete moved objects ?
Thank you for your work!

**Comment by wojnas** [comment]
It's safety to run?
db.rocketchat.rocketchat_uploads.chunks.remove({})

**Comment by geekgonecrazy** [comment]
in theory it should be.  Do a backup first though :)

**Comment by wojnas** [comment]
Hi, the attachments works fine after migration :). 
But I worried about future upgrade of RC versions and migrations on the database in mongo.
