### ISSUE TITLE
Support for Mongo5 (and use of new Mongo driver)

### ISSUE THREAD

**Issue by PiotrKrzyzek** [RocketChat/filestore-migrator#16]
Upon trying to connect to the RocketChat database, the migrator fails and errors out with a panic:

`panic: server returned error on SASL authentication step: BSON field 'saslContinue.mechanism' is an unknown field.`

If we search online for others with similar issues, the issue was always an outdated version of a Mongo driver for Go. Looking at the code here, it seems it's using a driver that does not support Mongo5. 

There is an official Mongo driver that is well supported and can connect to Mongo5 (which is the latest recommended version of Mongo for Rocketchat).

The current driver used is also unmaintained: https://github.com/go-mgo/mgo and as such should be replaced.

**Comment by debdutdeb** [comment]
Closed by #17
